In [2]:
import torch
import torch.nn as nn

In [11]:
#input 
torch.manual_seed(42)#same as random_state
inputs = torch.tensor([1.0, 2.0, 3.0])

In [12]:
neuron = nn.Linear(in_features = 3, out_features = 1)

output = neuron(inputs)

In [13]:
print(output)

tensor([1.5244], grad_fn=<ViewBackward0>)


In [14]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [15]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [16]:
#verify
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)